application: sidedrives
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: img/sd-favicon.ico
  upload: img/sd-favicon.ico

- url: /
  static_files: index.html
  upload: index.html

- url: /edit
  static_files: edit.html
  upload: edit.html

- url: /.*
  script: app.application

libraries:
- name: PIL
  version: 1.1.7
- name: numpy
  version: 1.6.1
